/* 当前初始化脚本截至sqlserver脚本的第013个文件 */

create table ACT_GE_PROPERTY (
    NAME_ NVARCHAR2(64),
    VALUE_ NVARCHAR2(300),
    REV_ INTEGER,
    primary key (NAME_)
);

insert into ACT_GE_PROPERTY
values ('schema.version', '5.9', 1);

insert into ACT_GE_PROPERTY
values ('schema.history', 'create(5.9)', 1);

insert into ACT_GE_PROPERTY
values ('next.dbid', '1', 1);

create table ACT_GE_BYTEARRAY (
    ID_ NVARCHAR2(64),
    REV_ INTEGER,
    NAME_ NVARCHAR2(255),
    DEPLOYMENT_ID_ NVARCHAR2(64),
    BYTES_ BLOB,
    GENERATED_ NUMBER(1,0) CHECK (GENERATED_ IN (1,0)),
    primary key (ID_)
);

create table ACT_RE_DEPLOYMENT (
    ID_ NVARCHAR2(64),
    NAME_ NVARCHAR2(255),
    DEPLOY_TIME_ TIMESTAMP(6),
    primary key (ID_)
);

create table ACT_RU_EXECUTION (
    ID_ NVARCHAR2(64),
    REV_ INTEGER,
    PROC_INST_ID_ NVARCHAR2(64),
    BUSINESS_KEY_ NVARCHAR2(255),
    PARENT_ID_ NVARCHAR2(64),
    PROC_DEF_ID_ NVARCHAR2(64),
    SUPER_EXEC_ NVARCHAR2(64),
    ACT_ID_ NVARCHAR2(255),
    IS_ACTIVE_ NUMBER(1,0) CHECK (IS_ACTIVE_ IN (1,0)),
    IS_CONCURRENT_ NUMBER(1,0) CHECK (IS_CONCURRENT_ IN (1,0)),
    IS_SCOPE_ NUMBER(1,0) CHECK (IS_SCOPE_ IN (1,0)),
    IS_EVENT_SCOPE_ NUMBER(1,0) CHECK (IS_EVENT_SCOPE_ IN (1,0)),
    SUSPENSION_STATE_ INTEGER,
    primary key (ID_)
);

create table ACT_RU_JOB (
    ID_ NVARCHAR2(64) NOT NULL,
    REV_ INTEGER,
    TYPE_ NVARCHAR2(255) NOT NULL,
    LOCK_EXP_TIME_ TIMESTAMP(6),
    LOCK_OWNER_ NVARCHAR2(255),
    EXCLUSIVE_ NUMBER(1,0) CHECK (EXCLUSIVE_ IN (1,0)),
    EXECUTION_ID_ NVARCHAR2(64),
    PROCESS_INSTANCE_ID_ NVARCHAR2(64),
    RETRIES_ INTEGER,
    EXCEPTION_STACK_ID_ NVARCHAR2(64),
    EXCEPTION_MSG_ NVARCHAR2(2000),
    DUEDATE_ TIMESTAMP(6),
    REPEAT_ NVARCHAR2(255),
    HANDLER_TYPE_ NVARCHAR2(255),
    HANDLER_CFG_ NVARCHAR2(2000),
    primary key (ID_)
);

create table ACT_RE_PROCDEF (
    ID_ NVARCHAR2(64),
    REV_ INTEGER,
    CATEGORY_ NVARCHAR2(255),
    NAME_ NVARCHAR2(255),
    KEY_ NVARCHAR2(255),
    VERSION_ INTEGER,
    DEPLOYMENT_ID_ NVARCHAR2(64),
    RESOURCE_NAME_ NVARCHAR2(2000),
    DGRM_RESOURCE_NAME_ varchar(4000),
    HAS_START_FORM_KEY_ NUMBER(1,0) CHECK (HAS_START_FORM_KEY_ IN (1,0)),
    SUSPENSION_STATE_ INTEGER,
    primary key (ID_)
);

create table ACT_RU_TASK (
    ID_ NVARCHAR2(64),
    REV_ INTEGER,
    EXECUTION_ID_ NVARCHAR2(64),
    PROC_INST_ID_ NVARCHAR2(64),
    PROC_DEF_ID_ NVARCHAR2(64),
    NAME_ NVARCHAR2(255),
    PARENT_TASK_ID_ NVARCHAR2(64),
    DESCRIPTION_ NVARCHAR2(2000),
    TASK_DEF_KEY_ NVARCHAR2(255),
    OWNER_ NVARCHAR2(64),
    ASSIGNEE_ NVARCHAR2(64),
    DELEGATION_ NVARCHAR2(64),
    PRIORITY_ INTEGER,
    CREATE_TIME_ TIMESTAMP(6),
    DUE_DATE_ TIMESTAMP(6),
    primary key (ID_)
);

create table ACT_RU_IDENTITYLINK (
    ID_ NVARCHAR2(64),
    REV_ INTEGER,
    GROUP_ID_ NVARCHAR2(64),
    TYPE_ NVARCHAR2(255),
    USER_ID_ NVARCHAR2(64),
    TASK_ID_ NVARCHAR2(64),
    primary key (ID_)
);

create table ACT_RU_VARIABLE (
    ID_ NVARCHAR2(64) not null,
    REV_ INTEGER,
    TYPE_ NVARCHAR2(255) not null,
    NAME_ NVARCHAR2(255) not null,
    EXECUTION_ID_ NVARCHAR2(64),
    PROC_INST_ID_ NVARCHAR2(64),
    TASK_ID_ NVARCHAR2(64),
    BYTEARRAY_ID_ NVARCHAR2(64),
    DOUBLE_ NUMBER(*,10),
    LONG_ NUMBER(19,0),
    TEXT_ NVARCHAR2(2000),
    TEXT2_ NVARCHAR2(2000),
    primary key (ID_)
);

create table ACT_RU_EVENT_SUBSCR (
    ID_ NVARCHAR2(64) not null,
    REV_ integer,
    EVENT_TYPE_ NVARCHAR2(255) not null,
    EVENT_NAME_ NVARCHAR2(255),
    EXECUTION_ID_ NVARCHAR2(64),
    PROC_INST_ID_ NVARCHAR2(64),
    ACTIVITY_ID_ NVARCHAR2(64),
    CONFIGURATION_ NVARCHAR2(255),
    CREATED_ TIMESTAMP(6) not null,
    primary key (ID_)
);

create index ACT_IDX_EXEC_BUSKEY on ACT_RU_EXECUTION(BUSINESS_KEY_);
create index ACT_IDX_TASK_CREATE on ACT_RU_TASK(CREATE_TIME_);
create index ACT_IDX_IDENT_LNK_USER on ACT_RU_IDENTITYLINK(USER_ID_);
create index ACT_IDX_IDENT_LNK_GROUP on ACT_RU_IDENTITYLINK(GROUP_ID_);
create index ACT_IDX_EVENT_SUBSCR_CONFIG_ on ACT_RU_EVENT_SUBSCR(CONFIGURATION_);

create index ACT_IDX_BYTEAR_DEPL on ACT_GE_BYTEARRAY(DEPLOYMENT_ID_);


create index ACT_IDX_EXE_PROCINST on ACT_RU_EXECUTION(PROC_INST_ID_);


create index ACT_IDX_EXE_PARENT on ACT_RU_EXECUTION(PARENT_ID_);

    
create index ACT_IDX_EXE_SUPER on ACT_RU_EXECUTION(SUPER_EXEC_);


create index ACT_IDX_TSKASS_TASK on ACT_RU_IDENTITYLINK(TASK_ID_);

    
create index ACT_IDX_TASK_EXEC on ACT_RU_TASK(EXECUTION_ID_);

    
create index ACT_IDX_TASK_PROCINST on ACT_RU_TASK(PROC_INST_ID_);

    
create index ACT_IDX_TASK_PROCDEF on ACT_RU_TASK(PROC_DEF_ID_);

  
create index ACT_IDX_VAR_EXE on ACT_RU_VARIABLE(EXECUTION_ID_);


create index ACT_IDX_VAR_PROCINST on ACT_RU_VARIABLE(PROC_INST_ID_);


create index ACT_IDX_VAR_BYTEARRAY on ACT_RU_VARIABLE(BYTEARRAY_ID_);


create index ACT_IDX_JOB_EXCEPTION on ACT_RU_JOB(EXCEPTION_STACK_ID_);

    
create index ACT_IDX_EVENT_SUBSCR on ACT_RU_EVENT_SUBSCR(EXECUTION_ID_);

    


    
create table ACT_HI_PROCINST (
    ID_ NVARCHAR2(64) not null,
    PROC_INST_ID_ NVARCHAR2(64) not null,
    BUSINESS_KEY_ NVARCHAR2(255),
    PROC_DEF_ID_ NVARCHAR2(64) not null,
    START_TIME_ TIMESTAMP(6) not null,
    END_TIME_ TIMESTAMP(6),
    DURATION_ NUMBER(19,0),
    START_USER_ID_ NVARCHAR2(255),
    START_ACT_ID_ NVARCHAR2(255),
    END_ACT_ID_ NVARCHAR2(255),
    SUPER_PROCESS_INSTANCE_ID_ NVARCHAR2(64),
    DELETE_REASON_ NVARCHAR2(2000),
    primary key (ID_),
    unique (PROC_INST_ID_)
);

create table ACT_HI_ACTINST (
    ID_ NVARCHAR2(64) not null,
    PROC_DEF_ID_ NVARCHAR2(64) not null,
    PROC_INST_ID_ NVARCHAR2(64) not null,
    EXECUTION_ID_ NVARCHAR2(64) not null,
    ACT_ID_ NVARCHAR2(255) not null,
    ACT_NAME_ NVARCHAR2(255),
    ACT_TYPE_ NVARCHAR2(255) not null,
    ASSIGNEE_ NVARCHAR2(64),
    START_TIME_ TIMESTAMP(6) not null,
    END_TIME_ TIMESTAMP(6),
    DURATION_ NUMBER(19,0),
    primary key (ID_)
);

create table ACT_HI_TASKINST (
    ID_ NVARCHAR2(64) not null,
    PROC_DEF_ID_ NVARCHAR2(64),
    TASK_DEF_KEY_ NVARCHAR2(255),
    PROC_INST_ID_ NVARCHAR2(64),
    EXECUTION_ID_ NVARCHAR2(64),
    PARENT_TASK_ID_ NVARCHAR2(64),
    NAME_ NVARCHAR2(255),
    DESCRIPTION_ NVARCHAR2(2000),
    OWNER_ NVARCHAR2(64),
    ASSIGNEE_ NVARCHAR2(64),
    START_TIME_ TIMESTAMP(6) not null,
    END_TIME_ TIMESTAMP(6),
    DURATION_ NUMBER(19,0),
    DELETE_REASON_ NVARCHAR2(2000),
    PRIORITY_ INTEGER,
    DUE_DATE_ TIMESTAMP(6),
    primary key (ID_)
);

create table ACT_HI_DETAIL (
    ID_ varchar(64) not null,
    TYPE_ NVARCHAR2(255) not null,
    PROC_INST_ID_ NVARCHAR2(64) not null,
    EXECUTION_ID_ NVARCHAR2(64) not null,
    TASK_ID_ NVARCHAR2(64),
    ACT_INST_ID_ NVARCHAR2(64),
    NAME_ NVARCHAR2(255) not null,
    VAR_TYPE_ NVARCHAR2(64),
    REV_ INTEGER,
    TIME_ TIMESTAMP(6) not null,
    BYTEARRAY_ID_ NVARCHAR2(64),
    DOUBLE_ NUMBER(*,10),
    LONG_ NUMBER(19,0),
    TEXT_ NVARCHAR2(2000),
    TEXT2_ NVARCHAR2(2000),
    primary key (ID_)
);

create table ACT_HI_COMMENT (
    ID_ NVARCHAR2(64) not null,
    TYPE_ NVARCHAR2(255),
    TIME_ TIMESTAMP(6) not null,
    USER_ID_ NVARCHAR2(255),
    TASK_ID_ NVARCHAR2(64),
    PROC_INST_ID_ NVARCHAR2(64),
    ACTION_ NVARCHAR2(255),
    MESSAGE_ NVARCHAR2(2000),
    FULL_MSG_ BLOB,
    primary key (ID_)
);

create table ACT_HI_ATTACHMENT (
    ID_ NVARCHAR2(64) not null,
    REV_ INTEGER,
    USER_ID_ NVARCHAR2(255),
    NAME_ NVARCHAR2(255),
    DESCRIPTION_ NVARCHAR2(2000),
    TYPE_ NVARCHAR2(255),
    TASK_ID_ NVARCHAR2(64),
    PROC_INST_ID_ NVARCHAR2(64),
    URL_ NVARCHAR2(2000),
    CONTENT_ID_ NVARCHAR2(64),
    primary key (ID_)
);

create index ACT_IDX_HI_PRO_INST_END on ACT_HI_PROCINST(END_TIME_);
create index ACT_IDX_HI_PRO_I_BUSKEY on ACT_HI_PROCINST(BUSINESS_KEY_);
create index ACT_IDX_HI_ACT_INST_START on ACT_HI_ACTINST(START_TIME_);
create index ACT_IDX_HI_ACT_INST_END on ACT_HI_ACTINST(END_TIME_);
create index ACT_IDX_HI_DETAIL_PROC_INST on ACT_HI_DETAIL(PROC_INST_ID_);
create index ACT_IDX_HI_DETAIL_ACT_INST on ACT_HI_DETAIL(ACT_INST_ID_);
create index ACT_IDX_HI_DETAIL_TIME on ACT_HI_DETAIL(TIME_);
create index ACT_IDX_HI_DETAIL_NAME on ACT_HI_DETAIL(NAME_);


create table ACT_ID_GROUP (
    ID_ NVARCHAR2(64),
    REV_ INTEGER,
    NAME_ NVARCHAR2(255),
    TYPE_ NVARCHAR2(255),
    primary key (ID_)
);

create table ACT_ID_MEMBERSHIP (
    USER_ID_ NVARCHAR2(64),
    GROUP_ID_ NVARCHAR2(64),
    primary key (USER_ID_, GROUP_ID_)
);

create table ACT_ID_USER (
    ID_ NVARCHAR2(64),
    REV_ INTEGER,
    FIRST_ NVARCHAR2(255),
    LAST_ NVARCHAR2(255),
    EMAIL_ NVARCHAR2(255),
    PWD_ NVARCHAR2(255),
    PICTURE_ID_ NVARCHAR2(64),
    primary key (ID_)
);

create table ACT_ID_INFO (
    ID_ NVARCHAR2(64),
    REV_ INTEGER,
    USER_ID_ NVARCHAR2(64),
    TYPE_ NVARCHAR2(64),
    KEY_ NVARCHAR2(255),
    VALUE_ NVARCHAR2(255),
    PASSWORD_ BLOB,
    PARENT_ID_ NVARCHAR2(255),
    primary key (ID_)
);

create index ACT_IDX_MEMB_GROUP on ACT_ID_MEMBERSHIP(GROUP_ID_);


create index ACT_IDX_MEMB_USER on ACT_ID_MEMBERSHIP(USER_ID_);

    


CREATE TABLE ACT_AN_AUDIT_HIS (sid varchar2(36) NOT NULL, proc_inst_id_ varchar2(128), unitname varchar2(1000), assignee varchar2(128), assigneename varchar2(128), result varchar2(200), taskname varchar2(1000), comment_ varchar2(4000), createtime timestamp, CONSTRAINT PK__ACT_AN_A__DDDFDD367E02B4CC PRIMARY KEY (sid));

CREATE TABLE SYS_USER (sid varchar2(200) NOT NULL, username varchar2(100), password varchar2(100), name varchar2(100), mail varchar2(200), parentusersid varchar2(200), extno varchar2(200), officephone varchar2(200), theme varchar2(100), creatorsid varchar2(36), creatorname varchar2(36), createtime timestamp, pwdquestion varchar2(1000), pwdanswer varchar2(1000), gender varchar2(1), CONSTRAINT PK__SYS_USER__5F141958 PRIMARY KEY (sid));
CREATE TABLE QRTZ_TRIGGERS (TRIGGER_NAME varchar2(200) NOT NULL, TRIGGER_GROUP varchar2(200) NOT NULL, JOB_NAME varchar2(200) NOT NULL, JOB_GROUP varchar2(200) NOT NULL, IS_VOLATILE varchar2(1) NOT NULL, DESCRIPTION varchar2(250), NEXT_FIRE_TIME number(19), PREV_FIRE_TIME number(19), PRIORITY number(10), TRIGGER_STATE varchar2(16) NOT NULL, TRIGGER_TYPE varchar2(8) NOT NULL, START_TIME number(19) NOT NULL, END_TIME number(19), CALENDAR_NAME varchar2(200), MISFIRE_INSTR number(5), JOB_DATA blob, CONSTRAINT PK_QRTZ_TRIGGERS PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP));
CREATE TABLE PROCESS_TASK_INFO (ID varchar2(50) NOT NULL, TASKID varchar2(50), TASKNAME varchar2(50), ACTORID varchar2(50), ACTORNAME varchar2(50), CREATETIME timestamp, DESCRIPTION varchar2(500), COMPLETEDTIME timestamp, PROCESSINSTANCEID varchar2(50), INCOME varchar2(150), OUTCOME varchar2(150), ACTIVITYTYPE varchar2(120), STATE number(10), ASSIGNNAME varchar2(150), FORMRESOURCENAME varchar2(400), ORIGINAL_ASSIGN_NAME varchar2(250), BUSINESSAGENT varchar2(250), COPYTO number(10), COPYPROCESSINSTANCEID varchar2(50), COPYPROCESSNAME varchar2(100), CONSTRAINT PK__PROCESS_TASK_INF__7B5B524B PRIMARY KEY (ID));
CREATE TABLE JBPM4_VARIABLE (DBID_ number(19, 0) NOT NULL, CLASS_ varchar2(255) NOT NULL, DBVERSION_ number(10, 0) NOT NULL, KEY_ varchar2(255), CONVERTER_ varchar2(255), HIST_ number(1, 0), EXECUTION_ number(19, 0), TASK_ number(19, 0), LOB_ number(19, 0), timestamp_VALUE_ timestamp, DOUBLE_VALUE_ float(53), CLASSNAME_ varchar2(255), LONG_VALUE_ number(19, 0), STRING_VALUE_ varchar2(255), TEXT_VALUE_ clob, EXESYS_ number(19, 0), CONSTRAINT PK__JBPM4_VA__EE2DF1FD59FA5E80 PRIMARY KEY (DBID_));
CREATE TABLE JBPM4_TASK (DBID_ number(19, 0) NOT NULL, CLASS_ char(1) NOT NULL, DBVERSION_ number(10, 0) NOT NULL, NAME_ varchar2(255), DESCR_ clob, STATE_ varchar2(255), SUSPHISTSTATE_ varchar2(255), ASSIGNEE_ varchar2(255), FORM_ varchar2(2000), PRIORITY_ number(10, 0), CREATE_ timestamp, DUEDATE_ timestamp, PROGRESS_ number(10, 0), SIGNALLING_ number(1, 0), EXECUTION_ID_ varchar2(255), ACTIVITY_NAME_ varchar2(255), HASVARS_ number(1, 0), SUPERTASK_ number(19, 0), EXECUTION_ number(19, 0), PROCINST_ number(19, 0), SWIMLANE_ number(19, 0), TASKDEFNAME_ varchar2(255), CONSTRAINT PK__JBPM4_TASK__571DF1D5 PRIMARY KEY (DBID_));
CREATE TABLE JBPM4_JOB (DBID_ number(19, 0) NOT NULL, CLASS_ varchar2(255) NOT NULL, DBVERSION_ number(10, 0) NOT NULL, DUEDATE_ timestamp, STATE_ varchar2(255), ISEXCLUSIVE_ number(1, 0), LOCKOWNER_ varchar2(255), LOCKEXPTIME_ timestamp, EXCEPTION_ clob, RETRIES_ number(10, 0), PROCESSINSTANCE_ number(19, 0), EXECUTION_ number(19, 0), CFG_ number(19, 0), SIGNAL_ varchar2(255), EVENT_ varchar2(255), REPEAT_ varchar2(255), CONSTRAINT PK__JBPM4_JO__EE2DF1FD6EF57B66 PRIMARY KEY (DBID_));
CREATE TABLE JBPM4_HIST_DETAIL (DBID_ number(19, 0) NOT NULL, CLASS_ varchar2(255) NOT NULL, DBVERSION_ number(10, 0) NOT NULL, USERID_ varchar2(255), TIME_ timestamp, HPROCI_ number(19, 0), HPROCIIDX_ number(10, 0), HACTI_ number(19, 0), HACTIIDX_ number(10, 0), HTASK_ number(19, 0), HTASKIDX_ number(10, 0), HVAR_ number(19, 0), HVARIDX_ number(10, 0), MESSAGE_ varchar2(255), OLD_STR_ varchar2(255), NEW_STR_ varchar2(255), OLD_INT_ number(10, 0), NEW_INT_ number(10, 0), OLD_TIME_ timestamp, NEW_TIME_ timestamp, PARENT_ number(19, 0), PARENT_IDX_ number(10, 0), CONSTRAINT PK__JBPM4_HI__EE2DF1FD09A971A2 PRIMARY KEY (DBID_));
CREATE TABLE JBPM4_HIST_ACTINST (DBID_ number(19, 0) NOT NULL, CLASS_ varchar2(255) NOT NULL, DBVERSION_ number(10, 0) NOT NULL, HPROCI_ number(19, 0), TYPE_ varchar2(255), EXECUTION_ varchar2(255), ACTIVITY_NAME_ varchar2(255), START_ timestamp, END_ timestamp, DURATION_ number(19, 0), TRANSITION_ varchar2(255), NEXTIDX_ number(10, 0), HTASK_ number(19, 0), CONSTRAINT PK__JBPM4_HI__EE2DF1FD0D7A0286 PRIMARY KEY (DBID_));
CREATE TABLE JBPM4_EXECUTION (DBID_ number(19, 0) NOT NULL, CLASS_ varchar2(255) NOT NULL, DBVERSION_ number(10, 0) NOT NULL, ACTIVITYNAME_ varchar2(255), PROCDEFID_ varchar2(255), HASVARS_ number(1, 0), NAME_ varchar2(255), KEY_ varchar2(255), ID_ varchar2(255), STATE_ varchar2(255), SUSPHISTSTATE_ varchar2(255), PRIORITY_ number(10, 0), HISACTINST_ number(19, 0), PARENT_ number(19, 0), INSTANCE_ number(19, 0), SUPEREXEC_ number(19, 0), SUBPROCINST_ number(19, 0), PARENT_IDX_ number(10, 0), CONSTRAINT PK__JBPM4_EX__EE2DF1FD114A936A PRIMARY KEY (DBID_), CONSTRAINT UQ__JBPM4_EX__C4971C0E14270015 UNIQUE (ID_));
CREATE TABLE CMS_ARTICLE (sid varchar2(100), article_title clob, article_content clob, create_date timestamp, modify_date timestamp, creator_name varchar2(200), article_keywords varchar2(200), article_resource varchar2(200), article_summary varchar2(500), creator_id varchar2(100), article_category varchar2(100), status varchar2(100), article_order number(10), clicktime number(10), article_att varchar2(50));

CREATE UNIQUE INDEX idx_forusername ON SYS_USER (username);

CREATE TABLE WORKITEMINFO (WORKITEMID number(19), CREATIONDATE timestamp, NAME varchar2(255), PROCESSINSTANCEID number(19) NOT NULL, STATE number(19) NOT NULL, OPTLOCK number(10), WORKITEMBYTEARRAY blob);
CREATE TABLE TMP_SYS_USER (sid varchar2(200) NOT NULL, username varchar2(100), password varchar2(100), name varchar2(100), mail varchar2(200), parentusersid varchar2(200), officephone varchar2(50), extno varchar2(50), CONSTRAINT PK_TMP_SYS_USER PRIMARY KEY (sid));

CREATE TABLE SYS_UNIT (sid varchar2(200) NOT NULL, parentsid varchar2(200), name varchar2(200), code varchar2(200), leaderusersid varchar2(200), unittype number(10), lastupdate timestamp, flag varchar2(1), unitsafb varchar2(200), CONSTRAINT PK__SYS_UNIT__66B53B20 PRIMARY KEY (sid));
CREATE TABLE SYS_FLOATREP_DBCOLINFO (sid varchar2(32) NOT NULL, colname varchar2(32), coltitle varchar2(32), colwidth float(10), edittype varchar2(32), sumtype varchar2(2000), tmplsid varchar2(32), dictsid varchar2(32), CONSTRAINT PK__SYS_FLOATREP_DBC__5BCD9859 PRIMARY KEY (sid));
CREATE TABLE SYS_FILES (sid varchar2(36) NOT NULL, filegroupsid varchar2(36), filename varchar2(100), filesize number(10), filedata blob, uploaddate timestamp, ispermanent number(1) DEFAULT '1', uploadtimeid varchar2(36), CONSTRAINT PK__SYS_FILE__DDDFDD362C3393D0 PRIMARY KEY (sid));
CREATE TABLE QRTZ_JOB_DETAILS (JOB_NAME varchar2(200) NOT NULL, JOB_GROUP varchar2(200) NOT NULL, DESCRIPTION varchar2(250), JOB_CLASS_NAME varchar2(250) NOT NULL, IS_DURABLE varchar2(1) NOT NULL, IS_VOLATILE varchar2(1) NOT NULL, IS_STATEFUL varchar2(1) NOT NULL, REQUESTS_RECOVERY varchar2(1) NOT NULL, JOB_DATA blob, CONSTRAINT PK_QRTZ_JOB_DETAILS PRIMARY KEY (JOB_NAME, JOB_GROUP));
CREATE TABLE QRTZ_FIRED_TRIGGERS (ENTRY_ID varchar2(95) NOT NULL, TRIGGER_NAME varchar2(200) NOT NULL, TRIGGER_GROUP varchar2(200) NOT NULL, IS_VOLATILE varchar2(1) NOT NULL, INSTANCE_NAME varchar2(200) NOT NULL, FIRED_TIME number(19) NOT NULL, PRIORITY number(10) NOT NULL, STATE varchar2(16) NOT NULL, JOB_NAME varchar2(200), JOB_GROUP varchar2(200), IS_STATEFUL varchar2(1), REQUESTS_RECOVERY varchar2(1), CONSTRAINT PK_QRTZ_FIRED_TRIGGERS PRIMARY KEY (ENTRY_ID));
CREATE TABLE PROCESSINSTANCEINFO (INSTANCEID number(19), LASTMODIFICATIONDATE timestamp, LASTREADDATE timestamp, PROCESSID varchar2(255), PROCESSINSTANCEBYTEARRAY blob, STARTDATE timestamp, STATE number(10) NOT NULL, OPTLOCK number(10), PROCESSNAME varchar2(250));
CREATE TABLE PROCESS_INSTANCE_INFO (ID varchar2(50) NOT NULL, PROCESSINSTANCEID varchar2(50), CREATOR varchar2(50), CREATEDATE timestamp, PROCESSNAME varchar2(100), PROCESSVERSION number(10), CONSTRAINT PK__PROCESS_INSTANCE__797309D9 PRIMARY KEY (ID));
CREATE TABLE PROCESS_DEFINITION (ID varchar2(50) NOT NULL, NAME varchar2(50), JSON_STR clob, XML_STR clob, NODE_JSON_STR clob, FLAG char(1), PROCESSVERSION number(10), CONSTRAINT PK__PROCESS_DEFINITI__778AC167 PRIMARY KEY (ID));
CREATE TABLE JBPM4_PARTICIPATION (DBID_ number(19, 0) NOT NULL, DBVERSION_ number(10, 0) NOT NULL, GROUPID_ varchar2(255), USERID_ varchar2(255), TYPE_ varchar2(255), TASK_ number(19, 0), SWIMLANE_ number(19, 0), CONSTRAINT PK__JBPM4_PA__EE2DF1FD6754599E PRIMARY KEY (DBID_));
CREATE TABLE JBPM4_ID_USER (DBID_ number(19, 0) NOT NULL, DBVERSION_ number(10, 0) NOT NULL, ID_ varchar2(255), PASSWORD_ varchar2(255), GIVENNAME_ varchar2(255), FAMILYNAME_ varchar2(255), BUSINESSEMAIL_ varchar2(255), CONSTRAINT PK__JBPM4_ID__EE2DF1FD72C60C4A PRIMARY KEY (DBID_));
CREATE TABLE JBPM4_HIST_VAR (DBID_ number(19, 0) NOT NULL, DBVERSION_ number(10, 0) NOT NULL, PROCINSTID_ varchar2(255), EXECUTIONID_ varchar2(255), VARNAME_ varchar2(255), VALUE_ varchar2(255), HPROCI_ number(19, 0), HTASK_ number(19, 0), CONSTRAINT PK__JBPM4_HI__EE2DF1FD7E37BEF6 PRIMARY KEY (DBID_));
CREATE TABLE JBPM4_HIST_TASK (DBID_ number(19, 0) NOT NULL, DBVERSION_ number(10, 0) NOT NULL, EXECUTION_ varchar2(255), OUTCOME_ varchar2(255), ASSIGNEE_ varchar2(255), PRIORITY_ number(10, 0), STATE_ varchar2(255), CREATE_ timestamp, END_ timestamp, DURATION_ number(19, 0), NEXTIDX_ number(10, 0), SUPERTASK_ number(19, 0), CONSTRAINT PK__JBPM4_HI__EE2DF1FD02084FDA PRIMARY KEY (DBID_));
CREATE TABLE JBPM4_HIST_PROCINST (DBID_ number(19, 0) NOT NULL, DBVERSION_ number(10, 0) NOT NULL, ID_ varchar2(255), PROCDEFID_ varchar2(255), KEY_ varchar2(255), START_ timestamp, END_ timestamp, DURATION_ number(19, 0), STATE_ varchar2(255), ENDACTIVITY_ varchar2(255), NEXTIDX_ number(10, 0), CONSTRAINT PK__JBPM4_HI__EE2DF1FD05D8E0BE PRIMARY KEY (DBID_));
CREATE TABLE CMS_CATEGORY (sid varchar2(50), category_title varchar2(100) NOT NULL, category_status varchar2(10), category_site varchar2(50), category_order number(10), creator varchar2(50), creator_dept varchar2(50), create_time timestamp);


CREATE TABLE SYS_REP_TMPL (sid varchar2(36) NOT NULL, groupsid varchar2(36), title varchar2(100), htmltable clob, dbtablename varchar2(100), isrelease number(10), CONSTRAINT PK__sys_rep_tmpl__6CA31EA0 PRIMARY KEY (sid));
CREATE TABLE JBPM4_ID_GROUP (DBID_ number(19, 0) NOT NULL, DBVERSION_ number(10, 0) NOT NULL, ID_ varchar2(255), NAME_ varchar2(255), TYPE_ varchar2(255), PARENT_ number(19, 0), CONSTRAINT PK__JBPM4_ID__EE2DF1FD7A672E12 PRIMARY KEY (DBID_));
CREATE TABLE JBPM4_DEPLOYPROP (DBID_ number(19, 0) NOT NULL, DEPLOYMENT_ number(19, 0), OBJNAME_ varchar2(255), KEY_ varchar2(255), STRINGVAL_ varchar2(255), LONGVAL_ number(19, 0), CONSTRAINT PK__JBPM4_DE__EE2DF1FD17F790F9 PRIMARY KEY (DBID_));
CREATE TABLE DEMO_BOOKORDER (sid varchar2(36) NOT NULL, bookname varchar2(400), creatorsid varchar2(36), creatorname varchar2(300), createtime timestamp, proc_inst_id_ varchar2(128), CONSTRAINT PK__DEMO_BOO__DDDFDD367A3223E8 PRIMARY KEY (sid));


CREATE TABLE PROCESSINSTANCELOG (ID number(19) NOT NULL, PROCESSINSTANCEID number(19), PROCESSID varchar2(255), START_DATE timestamp, END_DATE timestamp, CONSTRAINT PK__PROCESSI__3214EC2747DBAE45 PRIMARY KEY (ID));
CREATE SEQUENCE seq_PROCESSINSTANCELOG;


CREATE TABLE TMP_SYS_USER_UNIT_RELATE (usersid varchar2(200) NOT NULL, unitsid varchar2(200) NOT NULL, CONSTRAINT pkdbrelate_usersid_unitsid PRIMARY KEY (usersid, unitsid));
CREATE TABLE SYS_USER_UNIT_RELATE (usersid varchar2(200) NOT NULL, unitsid varchar2(200) NOT NULL, CONSTRAINT pk_sys_user_unit PRIMARY KEY (usersid, unitsid));
CREATE TABLE SYS_USER_ROLE_RELATE (usersid varchar2(200) NOT NULL, rolesid varchar2(200) NOT NULL, CONSTRAINT PK__SYS_USER_ROLE_RE__62E4AA3C PRIMARY KEY (usersid, rolesid));
CREATE TABLE SYS_ROLE (sid varchar2(200) NOT NULL, name varchar2(100), indexpath varchar2(500), flag varchar2(1), CONSTRAINT PK__SYS_ROLE__60FC61CA PRIMARY KEY (sid));
CREATE TABLE SYS_REP_DICT_ITEM (sid varchar2(36) NOT NULL, title varchar2(100), dict_sid varchar2(36), CONSTRAINT PK__SYS_REP___DDDFDD361367E606 PRIMARY KEY (sid));
CREATE TABLE SYS_REP_DICT (sid varchar2(36) NOT NULL, title varchar2(100), selectmode number(10), CONSTRAINT PK__SYS_REP___DDDFDD36173876EA PRIMARY KEY (sid));
CREATE TABLE SYS_OPTS (sid varchar2(36) NOT NULL, name varchar2(50), key_ varchar2(50), value varchar2(2000), enumxmlname varchar2(50), CONSTRAINT PK__SYS_OPTS__DDDFDD361B0907CE PRIMARY KEY (sid));
CREATE TABLE SYS_MULTI_UNITLEADER_RELATE (usersid varchar2(200) NOT NULL, unitsid varchar2(200) NOT NULL, CONSTRAINT PK__SYS_MULT__456FA6B21ED998B2 PRIMARY KEY (usersid, unitsid));
CREATE TABLE SYS_MAPREGION_UNIT_RELATE (sid varchar2(50) NOT NULL, regionsid varchar2(50), regionname varchar2(50), unitsid varchar2(200), unitname varchar2(200), CONSTRAINT PK__SYS_MAPR__DDDFDD3622AA2996 PRIMARY KEY (sid));
CREATE TABLE SYS_FLOATREP_TMPL (sid varchar2(32) NOT NULL, groupsid varchar2(32), title varchar2(100), dbtablename varchar2(100), isrelease number(1), CONSTRAINT PK__SYS_FLOA__DDDFDD36267ABA7A PRIMARY KEY (sid));
CREATE TABLE SYS_AUTHORITY (roleorusersid varchar2(200) NOT NULL, functionid varchar2(50) NOT NULL, CONSTRAINT PK__SYS_AUTHORITY__64CCF2AE PRIMARY KEY (roleorusersid, functionid));
CREATE TABLE QRTZ_TRIGGER_LISTENERS (TRIGGER_NAME varchar2(200) NOT NULL, TRIGGER_GROUP varchar2(200) NOT NULL, TRIGGER_LISTENER varchar2(200) NOT NULL, CONSTRAINT PK_QRTZ_TRIGGER_LISTENERS PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP, TRIGGER_LISTENER));
CREATE TABLE QRTZ_SIMPLE_TRIGGERS (TRIGGER_NAME varchar2(200) NOT NULL, TRIGGER_GROUP varchar2(200) NOT NULL, REPEAT_COUNT number(19) NOT NULL, REPEAT_INTERVAL number(19) NOT NULL, TIMES_TRIGGERED number(19) NOT NULL, CONSTRAINT PK_QRTZ_SIMPLE_TRIGGERS PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP));
CREATE TABLE QRTZ_SCHEDULER_STATE (INSTANCE_NAME varchar2(200) NOT NULL, LAST_CHECKIN_TIME number(19) NOT NULL, CHECKIN_INTERVAL number(19) NOT NULL, CONSTRAINT PK_QRTZ_SCHEDULER_STATE PRIMARY KEY (INSTANCE_NAME));
CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS (TRIGGER_GROUP varchar2(200) NOT NULL, CONSTRAINT PK_QRTZ_PAUSED_TRIGGER_GRPS PRIMARY KEY (TRIGGER_GROUP));
CREATE TABLE QRTZ_LOCKS (LOCK_NAME varchar2(40) NOT NULL, CONSTRAINT PK_QRTZ_LOCKS PRIMARY KEY (LOCK_NAME));
CREATE TABLE QRTZ_JOB_LISTENERS (JOB_NAME varchar2(200) NOT NULL, JOB_GROUP varchar2(200) NOT NULL, JOB_LISTENER varchar2(200) NOT NULL, CONSTRAINT PK_QRTZ_JOB_LISTENERS PRIMARY KEY (JOB_NAME, JOB_GROUP, JOB_LISTENER));
CREATE TABLE QRTZ_CRON_TRIGGERS (TRIGGER_NAME varchar2(200) NOT NULL, TRIGGER_GROUP varchar2(200) NOT NULL, CRON_EXPRESSION varchar2(120) NOT NULL, TIME_ZONE_ID varchar2(80), CONSTRAINT PK_QRTZ_CRON_TRIGGERS PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP));
CREATE TABLE QRTZ_CALENDARS (CALENDAR_NAME varchar2(200) NOT NULL, CALENDAR blob NOT NULL, CONSTRAINT PK_QRTZ_CALENDARS PRIMARY KEY (CALENDAR_NAME));
CREATE TABLE QRTZ_BLOB_TRIGGERS (TRIGGER_NAME varchar2(200) NOT NULL, TRIGGER_GROUP varchar2(200) NOT NULL, BLOB_DATA blob);
CREATE TABLE PROCESSDEF_PROCESSPUB_INFO (ID varchar2(32) NOT NULL, DEPLOYMENT_ID varchar2(32), PROCESSDEF_ID varchar2(32), CONSTRAINT PK__PROCESSD__3214EC274CA06362 PRIMARY KEY (ID));
CREATE TABLE PROCESS_NEXTMAN (sid varchar2(36) NOT NULL, processid varchar2(36), username varchar2(50), name varchar2(20), taskid varchar2(36), CONSTRAINT PK__PROCESS___DDDFDD3652593CB8 PRIMARY KEY (sid));
CREATE TABLE JBPM4_SWIMLANE (DBID_ number(19, 0) NOT NULL, DBVERSION_ number(10, 0) NOT NULL, NAME_ varchar2(255), ASSIGNEE_ varchar2(255), EXECUTION_ number(19, 0), CONSTRAINT PK__JBPM4_SW__EE2DF1FD5FB337D6 PRIMARY KEY (DBID_));
CREATE TABLE JBPM4_PROPERTY (KEY_ varchar2(255) NOT NULL, VERSION_ number(10, 0) NOT NULL, VALUE_ varchar2(255), CONSTRAINT PK__JBPM4_PR__6AF90CE36383C8BA PRIMARY KEY (KEY_));
CREATE TABLE JBPM4_LOB (DBID_ number(19, 0) NOT NULL, DBVERSION_ number(10, 0) NOT NULL, BLOB_VALUE_ blob, DEPLOYMENT_ number(19, 0), NAME_ clob, CONSTRAINT PK__JBPM4_LO__EE2DF1FD6B24EA82 PRIMARY KEY (DBID_));
CREATE TABLE JBPM4_ID_MEMBERSHIP (DBID_ number(19, 0) NOT NULL, DBVERSION_ number(10, 0) NOT NULL, USER_ number(19, 0), GROUP_ number(19, 0), NAME_ varchar2(255), CONSTRAINT PK__JBPM4_ID__EE2DF1FD76969D2E PRIMARY KEY (DBID_));
CREATE TABLE JBPM4_DEPLOYMENT (DBID_ number(19, 0) NOT NULL, NAME_ varchar2(255), TIMESTAMP_ number(19, 0), STATE_ varchar2(255), CONSTRAINT PK__JBPM4_DE__EE2DF1FD1BC821DD PRIMARY KEY (DBID_));
CREATE TABLE DEMO_SINGLE_DATAGRID (sid varchar2(36) NOT NULL, name varchar2(300), treenode_sid varchar2(36), CONSTRAINT PK__DEMO_SIN__DDDFDD36236943A5 PRIMARY KEY (sid));
CREATE TABLE DEMO_LEFT_TREE (sid varchar2(36) NOT NULL, name varchar2(500), parentsid varchar2(36) NOT NULL, CONSTRAINT PK__DEMO_LEF__DDDFDD362739D489 PRIMARY KEY (sid));


INSERT INTO SYS_USER_UNIT_RELATE (usersid, unitsid) VALUES ('1234', 'orgroot');
INSERT INTO SYS_USER_ROLE_RELATE (usersid, rolesid) VALUES ('1234', '153');
INSERT INTO SYS_USER (sid, username, password, name, mail, parentusersid, extno, officephone, theme, creatorsid, creatorname, createtime, pwdquestion, pwdanswer, gender) VALUES ('1234', 'admin', '0DPiKuNIrrVmD8IUCuw1hQxNqZc=', '系统管理员', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO SYS_ROLE (sid, name, indexpath, flag) VALUES ('153', '系统管理员', NULL, NULL);
INSERT INTO QRTZ_LOCKS (LOCK_NAME) VALUES ('CALENDAR_ACCESS');
INSERT INTO QRTZ_LOCKS (LOCK_NAME) VALUES ('JOB_ACCESS');
INSERT INTO QRTZ_LOCKS (LOCK_NAME) VALUES ('MISFIRE_ACCESS');
INSERT INTO QRTZ_LOCKS (LOCK_NAME) VALUES ('STATE_ACCESS');
INSERT INTO QRTZ_LOCKS (LOCK_NAME) VALUES ('TRIGGER_ACCESS');
INSERT INTO DEMO_SINGLE_DATAGRID (sid, name, treenode_sid) VALUES ('1234', '测试记录', NULL);


INSERT INTO ACT_GE_PROPERTY (NAME_, VALUE_, REV_) VALUES ('historyLevel', '3', 1);
