

drop index ACT_UNIQ_RU_BUS_KEY on ACT_RU_EXECUTION;

alter table ACT_RU_EXECUTION add index ACT_UNIQ_RU_BUS_KEY (PROC_DEF_ID_, BUSINESS_KEY_);


drop index ACT_UNIQ_HI_BUS_KEY on ACT_HI_PROCINST;

alter table ACT_HI_PROCINST add index ACT_UNIQ_HI_BUS_KEY (PROC_DEF_ID_, BUSINESS_KEY_);

