
/****** Object:  Table [dbo].[WORKITEMINFO]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[WORKITEMINFO](
	[WORKITEMID] [bigint] NULL,
	[CREATIONDATE] [datetime] NULL,
	[NAME] [varchar](255) NULL,
	[PROCESSINSTANCEID] [bigint] NOT NULL,
	[STATE] [bigint] NOT NULL,
	[OPTLOCK] [int] NULL,
	[WORKITEMBYTEARRAY] [image] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[TMP_SYS_USER_UNIT_RELATE]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[TMP_SYS_USER_UNIT_RELATE](
	[usersid] [varchar](200) NOT NULL,
	[unitsid] [varchar](200) NOT NULL,
 CONSTRAINT [pkdbrelate_usersid_unitsid] PRIMARY KEY CLUSTERED 
(
	[usersid] ASC,
	[unitsid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[TMP_SYS_USER]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[TMP_SYS_USER](
	[sid] [varchar](200) NOT NULL,
	[username] [varchar](100) NULL,
	[password] [varchar](100) NULL,
	[name] [varchar](100) NULL,
	[mail] [varchar](200) NULL,
	[parentusersid] [varchar](200) NULL,
	[officephone] [varchar](50) NULL,
	[extno] [varchar](50) NULL,
 CONSTRAINT [PK_TMP_SYS_USER] PRIMARY KEY CLUSTERED 
(
	[sid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[TMP_SYS_UNIT]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[TMP_SYS_UNIT](
	[sid] [varchar](200) NOT NULL,
	[parentsid] [varchar](200) NULL,
	[name] [varchar](200) NULL,
	[code] [varchar](200) NOT NULL,
	[leaderusersid] [varchar](200) NULL,
	[unittype] [varchar](50) NULL,
	[lastupdate] [datetime] NULL,
	[flag] [varchar](1) NULL,
 CONSTRAINT [PK_TMP_SYS_UNIT] PRIMARY KEY CLUSTERED 
(
	[sid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[SYS_USER_UNIT_RELATE]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[SYS_USER_UNIT_RELATE](
	[usersid] [varchar](200) NOT NULL,
	[unitsid] [varchar](200) NOT NULL,
 CONSTRAINT [pk_sys_user_unit] PRIMARY KEY CLUSTERED 
(
	[usersid] ASC,
	[unitsid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
INSERT [dbo].[SYS_USER_UNIT_RELATE] ([usersid], [unitsid]) VALUES (N'1234', N'orgroot')
/****** Object:  Table [dbo].[SYS_USER_ROLE_RELATE]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[SYS_USER_ROLE_RELATE](
	[usersid] [varchar](200) NOT NULL,
	[rolesid] [varchar](200) NOT NULL,
 CONSTRAINT [PK__SYS_USER_ROLE_RE__62E4AA3C] PRIMARY KEY CLUSTERED 
(
	[usersid] ASC,
	[rolesid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
INSERT [dbo].[SYS_USER_ROLE_RELATE] ([usersid], [rolesid]) VALUES (N'1234', N'153')
/****** Object:  Table [dbo].[SYS_USER]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[SYS_USER](
	[sid] [varchar](200) NOT NULL,
	[username] [varchar](100) NULL,
	[password] [varchar](100) NULL,
	[name] [varchar](100) NULL,
	[mail] [varchar](200) NULL,
	[parentusersid] [varchar](200) NULL,
	[extno] [varchar](200) NULL,
	[officephone] [varchar](200) NULL
) ON [PRIMARY]
SET ANSI_PADDING OFF
ALTER TABLE [dbo].[SYS_USER] ADD [theme] [varchar](100) NULL
ALTER TABLE [dbo].[SYS_USER] ADD [creatorsid] [varchar](36) NULL
ALTER TABLE [dbo].[SYS_USER] ADD [creatorname] [varchar](36) NULL
ALTER TABLE [dbo].[SYS_USER] ADD [createtime] [datetime] NULL
ALTER TABLE [dbo].[SYS_USER] ADD  CONSTRAINT [PK__SYS_USER__5F141958] PRIMARY KEY CLUSTERED 
(
	[sid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY];
SET ANSI_PADDING OFF;
INSERT [dbo].[SYS_USER] ([sid], [username], [password], [name], [mail], [parentusersid], [extno], [officephone], [theme], [creatorsid], [creatorname], [createtime]) VALUES (N'1234', N'admin', N'0DPiKuNIrrVmD8IUCuw1hQxNqZc=', N'系统管理员', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
/****** Object:  Table [dbo].[SYS_UNIT]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[SYS_UNIT](
	[sid] [varchar](200) NOT NULL,
	[parentsid] [varchar](200) NULL,
	[name] [varchar](200) NULL,
	[code] [varchar](200) NULL,
	[leaderusersid] [varchar](200) NULL,
	[unittype] [int] NULL,
	[lastupdate] [datetime] NULL,
	[flag] [varchar](1) NULL,
	[unitsafb] [varchar](200) NULL,
 CONSTRAINT [PK__SYS_UNIT__66B53B20] PRIMARY KEY CLUSTERED 
(
	[sid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[SYS_ROLE]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[SYS_ROLE](
	[sid] [varchar](200) NOT NULL,
	[name] [varchar](100) NULL,
 CONSTRAINT [PK__SYS_ROLE__60FC61CA] PRIMARY KEY CLUSTERED 
(
	[sid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
INSERT [dbo].[SYS_ROLE] ([sid], [name]) VALUES (N'153', N'系统管理员')
/****** Object:  Table [dbo].[SYS_REP_TMPL]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[SYS_REP_TMPL](
	[sid] [varchar](36) NOT NULL,
	[groupsid] [varchar](36) NULL,
	[title] [varchar](100) NULL,
	[htmltable] [text] NULL,
	[dbtablename] [varchar](100) NULL,
	[isrelease] [int] NULL,
 CONSTRAINT [PK__sys_rep_tmpl__6CA31EA0] PRIMARY KEY CLUSTERED 
(
	[sid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[SYS_REP_DICT_ITEM]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[SYS_REP_DICT_ITEM](
	[sid] [varchar](36) NOT NULL,
	[title] [varchar](100) NULL,
	[dict_sid] [varchar](36) NULL,
PRIMARY KEY CLUSTERED 
(
	[sid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[SYS_REP_DICT]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[SYS_REP_DICT](
	[sid] [varchar](36) NOT NULL,
	[title] [varchar](100) NULL,
	[selectmode] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[sid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[SYS_OPTS]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING OFF;
CREATE TABLE [dbo].[SYS_OPTS](
	[sid] [varchar](36) NOT NULL,
	[name] [varchar](50) NULL,
	[key_] [varchar](50) NULL,
	[value] [varchar](4000) NULL,
	[enumxmlname] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[sid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[SYS_MULTI_UNITLEADER_RELATE]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[SYS_MULTI_UNITLEADER_RELATE](
	[usersid] [varchar](200) NOT NULL,
	[unitsid] [varchar](200) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[usersid] ASC,
	[unitsid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[SYS_MAPREGION_UNIT_RELATE]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[SYS_MAPREGION_UNIT_RELATE](
	[sid] [varchar](50) NOT NULL,
	[regionsid] [varchar](50) NULL,
	[regionname] [varchar](50) NULL,
	[unitsid] [varchar](200) NULL,
	[unitname] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[sid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[SYS_FLOATREP_TMPL]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[SYS_FLOATREP_TMPL](
	[sid] [varchar](32) NOT NULL,
	[groupsid] [varchar](32) NULL,
	[title] [varchar](100) NULL,
	[dbtablename] [varchar](100) NULL,
	[isrelease] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[sid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[SYS_FLOATREP_DBCOLINFO]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[SYS_FLOATREP_DBCOLINFO](
	[sid] [varchar](32) NOT NULL,
	[colname] [varchar](32) NULL,
	[coltitle] [varchar](32) NULL,
	[colwidth] [real] NULL,
	[edittype] [varchar](32) NULL,
	[sumtype] [varchar](2000) NULL,
	[tmplsid] [varchar](32) NULL,
	[dictsid] [varchar](32) NULL,
 CONSTRAINT [PK__SYS_FLOATREP_DBC__5BCD9859] PRIMARY KEY CLUSTERED 
(
	[sid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[SYS_FILES]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[SYS_FILES](
	[sid] [varchar](36) NOT NULL,
	[filegroupsid] [varchar](36) NULL,
	[filename] [varchar](100) NULL,
	[filesize] [int] NULL,
	[filedata] [image] NULL,
	[uploaddate] [datetime] NULL,
	[ispermanent] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
SET ANSI_PADDING OFF
ALTER TABLE [dbo].[SYS_FILES] ADD [uploadtimeid] [varchar](36) NULL
ALTER TABLE [dbo].[SYS_FILES] ADD PRIMARY KEY CLUSTERED 
(
	[sid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[SYS_AUTHORITY]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[SYS_AUTHORITY](
	[roleorusersid] [varchar](200) NOT NULL,
	[functionid] [varchar](50) NOT NULL,
 CONSTRAINT [PK__SYS_AUTHORITY__64CCF2AE] PRIMARY KEY CLUSTERED 
(
	[roleorusersid] ASC,
	[functionid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[QRTZ_TRIGGERS]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[QRTZ_TRIGGERS](
	[TRIGGER_NAME] [varchar](200) NOT NULL,
	[TRIGGER_GROUP] [varchar](200) NOT NULL,
	[JOB_NAME] [varchar](200) NOT NULL,
	[JOB_GROUP] [varchar](200) NOT NULL,
	[IS_VOLATILE] [varchar](1) NOT NULL,
	[DESCRIPTION] [varchar](250) NULL,
	[NEXT_FIRE_TIME] [bigint] NULL,
	[PREV_FIRE_TIME] [bigint] NULL,
	[PRIORITY] [int] NULL,
	[TRIGGER_STATE] [varchar](16) NOT NULL,
	[TRIGGER_TYPE] [varchar](8) NOT NULL,
	[START_TIME] [bigint] NOT NULL,
	[END_TIME] [bigint] NULL,
	[CALENDAR_NAME] [varchar](200) NULL,
	[MISFIRE_INSTR] [smallint] NULL,
	[JOB_DATA] [image] NULL,
 CONSTRAINT [PK_QRTZ_TRIGGERS] PRIMARY KEY CLUSTERED 
(
	[TRIGGER_NAME] ASC,
	[TRIGGER_GROUP] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[QRTZ_TRIGGER_LISTENERS]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[QRTZ_TRIGGER_LISTENERS](
	[TRIGGER_NAME] [varchar](200) NOT NULL,
	[TRIGGER_GROUP] [varchar](200) NOT NULL,
	[TRIGGER_LISTENER] [varchar](200) NOT NULL,
 CONSTRAINT [PK_QRTZ_TRIGGER_LISTENERS] PRIMARY KEY CLUSTERED 
(
	[TRIGGER_NAME] ASC,
	[TRIGGER_GROUP] ASC,
	[TRIGGER_LISTENER] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[QRTZ_SIMPLE_TRIGGERS]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[QRTZ_SIMPLE_TRIGGERS](
	[TRIGGER_NAME] [varchar](200) NOT NULL,
	[TRIGGER_GROUP] [varchar](200) NOT NULL,
	[REPEAT_COUNT] [bigint] NOT NULL,
	[REPEAT_INTERVAL] [bigint] NOT NULL,
	[TIMES_TRIGGERED] [bigint] NOT NULL,
 CONSTRAINT [PK_QRTZ_SIMPLE_TRIGGERS] PRIMARY KEY CLUSTERED 
(
	[TRIGGER_NAME] ASC,
	[TRIGGER_GROUP] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[QRTZ_SCHEDULER_STATE]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[QRTZ_SCHEDULER_STATE](
	[INSTANCE_NAME] [varchar](200) NOT NULL,
	[LAST_CHECKIN_TIME] [bigint] NOT NULL,
	[CHECKIN_INTERVAL] [bigint] NOT NULL,
 CONSTRAINT [PK_QRTZ_SCHEDULER_STATE] PRIMARY KEY CLUSTERED 
(
	[INSTANCE_NAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[QRTZ_PAUSED_TRIGGER_GRPS]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[QRTZ_PAUSED_TRIGGER_GRPS](
	[TRIGGER_GROUP] [varchar](200) NOT NULL,
 CONSTRAINT [PK_QRTZ_PAUSED_TRIGGER_GRPS] PRIMARY KEY CLUSTERED 
(
	[TRIGGER_GROUP] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[QRTZ_LOCKS]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[QRTZ_LOCKS](
	[LOCK_NAME] [varchar](40) NOT NULL,
 CONSTRAINT [PK_QRTZ_LOCKS] PRIMARY KEY CLUSTERED 
(
	[LOCK_NAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
INSERT [dbo].[QRTZ_LOCKS] ([LOCK_NAME]) VALUES (N'CALENDAR_ACCESS')
INSERT [dbo].[QRTZ_LOCKS] ([LOCK_NAME]) VALUES (N'JOB_ACCESS')
INSERT [dbo].[QRTZ_LOCKS] ([LOCK_NAME]) VALUES (N'MISFIRE_ACCESS')
INSERT [dbo].[QRTZ_LOCKS] ([LOCK_NAME]) VALUES (N'STATE_ACCESS')
INSERT [dbo].[QRTZ_LOCKS] ([LOCK_NAME]) VALUES (N'TRIGGER_ACCESS')
/****** Object:  Table [dbo].[QRTZ_JOB_LISTENERS]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[QRTZ_JOB_LISTENERS](
	[JOB_NAME] [varchar](200) NOT NULL,
	[JOB_GROUP] [varchar](200) NOT NULL,
	[JOB_LISTENER] [varchar](200) NOT NULL,
 CONSTRAINT [PK_QRTZ_JOB_LISTENERS] PRIMARY KEY CLUSTERED 
(
	[JOB_NAME] ASC,
	[JOB_GROUP] ASC,
	[JOB_LISTENER] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[QRTZ_JOB_DETAILS]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[QRTZ_JOB_DETAILS](
	[JOB_NAME] [varchar](200) NOT NULL,
	[JOB_GROUP] [varchar](200) NOT NULL,
	[DESCRIPTION] [varchar](250) NULL,
	[JOB_CLASS_NAME] [varchar](250) NOT NULL,
	[IS_DURABLE] [varchar](1) NOT NULL,
	[IS_VOLATILE] [varchar](1) NOT NULL,
	[IS_STATEFUL] [varchar](1) NOT NULL,
	[REQUESTS_RECOVERY] [varchar](1) NOT NULL,
	[JOB_DATA] [image] NULL,
 CONSTRAINT [PK_QRTZ_JOB_DETAILS] PRIMARY KEY CLUSTERED 
(
	[JOB_NAME] ASC,
	[JOB_GROUP] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[QRTZ_FIRED_TRIGGERS]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[QRTZ_FIRED_TRIGGERS](
	[ENTRY_ID] [varchar](95) NOT NULL,
	[TRIGGER_NAME] [varchar](200) NOT NULL,
	[TRIGGER_GROUP] [varchar](200) NOT NULL,
	[IS_VOLATILE] [varchar](1) NOT NULL,
	[INSTANCE_NAME] [varchar](200) NOT NULL,
	[FIRED_TIME] [bigint] NOT NULL,
	[PRIORITY] [int] NOT NULL,
	[STATE] [varchar](16) NOT NULL,
	[JOB_NAME] [varchar](200) NULL,
	[JOB_GROUP] [varchar](200) NULL,
	[IS_STATEFUL] [varchar](1) NULL,
	[REQUESTS_RECOVERY] [varchar](1) NULL,
 CONSTRAINT [PK_QRTZ_FIRED_TRIGGERS] PRIMARY KEY CLUSTERED 
(
	[ENTRY_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[QRTZ_CRON_TRIGGERS]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[QRTZ_CRON_TRIGGERS](
	[TRIGGER_NAME] [varchar](200) NOT NULL,
	[TRIGGER_GROUP] [varchar](200) NOT NULL,
	[CRON_EXPRESSION] [varchar](120) NOT NULL,
	[TIME_ZONE_ID] [varchar](80) NULL,
 CONSTRAINT [PK_QRTZ_CRON_TRIGGERS] PRIMARY KEY CLUSTERED 
(
	[TRIGGER_NAME] ASC,
	[TRIGGER_GROUP] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[QRTZ_CALENDARS]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[QRTZ_CALENDARS](
	[CALENDAR_NAME] [varchar](200) NOT NULL,
	[CALENDAR] [image] NOT NULL,
 CONSTRAINT [PK_QRTZ_CALENDARS] PRIMARY KEY CLUSTERED 
(
	[CALENDAR_NAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[QRTZ_BLOB_TRIGGERS]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[QRTZ_BLOB_TRIGGERS](
	[TRIGGER_NAME] [varchar](200) NOT NULL,
	[TRIGGER_GROUP] [varchar](200) NOT NULL,
	[BLOB_DATA] [image] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[PROCESSINSTANCELOG]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[PROCESSINSTANCELOG](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PROCESSINSTANCEID] [bigint] NULL,
	[PROCESSID] [varchar](255) NULL,
	[START_DATE] [datetime] NULL,
	[END_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[PROCESSINSTANCEINFO]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[PROCESSINSTANCEINFO](
	[INSTANCEID] [bigint] NULL,
	[LASTMODIFICATIONDATE] [datetime] NULL,
	[LASTREADDATE] [datetime] NULL,
	[PROCESSID] [varchar](255) NULL,
	[PROCESSINSTANCEBYTEARRAY] [image] NULL,
	[STARTDATE] [datetime] NULL,
	[STATE] [int] NOT NULL,
	[OPTLOCK] [int] NULL,
	[PROCESSNAME] [varchar](250) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[PROCESSDEF_PROCESSPUB_INFO]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[PROCESSDEF_PROCESSPUB_INFO](
	[ID] [varchar](32) NOT NULL,
	[DEPLOYMENT_ID] [varchar](32) NULL,
	[PROCESSDEF_ID] [varchar](32) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[PROCESS_TASK_INFO]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[PROCESS_TASK_INFO](
	[ID] [varchar](50) NOT NULL,
	[TASKID] [varchar](50) NULL,
	[TASKNAME] [varchar](50) NULL,
	[ACTORID] [varchar](50) NULL,
	[ACTORNAME] [varchar](50) NULL,
	[CREATETIME] [datetime] NULL,
	[DESCRIPTION] [varchar](500) NULL,
	[COMPLETEDTIME] [datetime] NULL,
	[PROCESSINSTANCEID] [varchar](50) NULL,
	[INCOME] [varchar](150) NULL,
	[OUTCOME] [varchar](150) NULL,
	[ACTIVITYTYPE] [varchar](120) NULL,
	[STATE] [int] NULL,
	[ASSIGNNAME] [varchar](150) NULL,
	[FORMRESOURCENAME] [varchar](400) NULL,
	[ORIGINAL_ASSIGN_NAME] [varchar](250) NULL,
	[BUSINESSAGENT] [varchar](250) NULL,
	[COPYTO] [int] NULL,
	[COPYPROCESSINSTANCEID] [varchar](50) NULL,
	[COPYPROCESSNAME] [varchar](100) NULL,
 CONSTRAINT [PK__PROCESS_TASK_INF__7B5B524B] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[PROCESS_NEXTMAN]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[PROCESS_NEXTMAN](
	[sid] [varchar](36) NOT NULL,
	[processid] [varchar](36) NULL,
	[username] [varchar](50) NULL,
	[name] [varchar](20) NULL,
	[taskid] [varchar](36) NULL,
PRIMARY KEY CLUSTERED 
(
	[sid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[PROCESS_INSTANCE_INFO]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[PROCESS_INSTANCE_INFO](
	[ID] [varchar](50) NOT NULL,
	[PROCESSINSTANCEID] [varchar](50) NULL,
	[CREATOR] [varchar](50) NULL,
	[CREATEDATE] [datetime] NULL,
	[PROCESSNAME] [varchar](100) NULL,
	[PROCESSVERSION] [int] NULL,
 CONSTRAINT [PK__PROCESS_INSTANCE__797309D9] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[PROCESS_DEFINITION]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[PROCESS_DEFINITION](
	[ID] [varchar](50) NOT NULL,
	[NAME] [varchar](50) NULL,
	[JSON_STR] [text] NULL,
	[XML_STR] [text] NULL,
	[NODE_JSON_STR] [text] NULL,
	[FLAG] [char](1) NULL,
	[PROCESSVERSION] [int] NULL,
 CONSTRAINT [PK__PROCESS_DEFINITI__778AC167] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[JBPM4_VARIABLE]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[JBPM4_VARIABLE](
	[DBID_] [numeric](19, 0) NOT NULL,
	[CLASS_] [varchar](255) NOT NULL,
	[DBVERSION_] [numeric](10, 0) NOT NULL,
	[KEY_] [varchar](255) NULL,
	[CONVERTER_] [varchar](255) NULL,
	[HIST_] [numeric](1, 0) NULL,
	[EXECUTION_] [numeric](19, 0) NULL,
	[TASK_] [numeric](19, 0) NULL,
	[LOB_] [numeric](19, 0) NULL,
	[DATE_VALUE_] [datetime] NULL,
	[DOUBLE_VALUE_] [float] NULL,
	[CLASSNAME_] [varchar](255) NULL,
	[LONG_VALUE_] [numeric](19, 0) NULL,
	[STRING_VALUE_] [varchar](255) NULL,
	[TEXT_VALUE_] [text] NULL,
	[EXESYS_] [numeric](19, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[DBID_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[JBPM4_TASK]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[JBPM4_TASK](
	[DBID_] [numeric](19, 0) NOT NULL,
	[CLASS_] [char](1) NOT NULL,
	[DBVERSION_] [numeric](10, 0) NOT NULL,
	[NAME_] [varchar](255) NULL,
	[DESCR_] [text] NULL,
	[STATE_] [varchar](255) NULL,
	[SUSPHISTSTATE_] [varchar](255) NULL,
	[ASSIGNEE_] [varchar](255) NULL,
	[FORM_] [varchar](2000) NULL,
	[PRIORITY_] [numeric](10, 0) NULL,
	[CREATE_] [datetime] NULL,
	[DUEDATE_] [datetime] NULL,
	[PROGRESS_] [numeric](10, 0) NULL,
	[SIGNALLING_] [numeric](1, 0) NULL,
	[EXECUTION_ID_] [varchar](255) NULL,
	[ACTIVITY_NAME_] [varchar](255) NULL,
	[HASVARS_] [numeric](1, 0) NULL,
	[SUPERTASK_] [numeric](19, 0) NULL,
	[EXECUTION_] [numeric](19, 0) NULL,
	[PROCINST_] [numeric](19, 0) NULL,
	[SWIMLANE_] [numeric](19, 0) NULL,
	[TASKDEFNAME_] [varchar](255) NULL,
 CONSTRAINT [PK__JBPM4_TASK__571DF1D5] PRIMARY KEY CLUSTERED 
(
	[DBID_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[JBPM4_SWIMLANE]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[JBPM4_SWIMLANE](
	[DBID_] [numeric](19, 0) NOT NULL,
	[DBVERSION_] [numeric](10, 0) NOT NULL,
	[NAME_] [varchar](255) NULL,
	[ASSIGNEE_] [varchar](255) NULL,
	[EXECUTION_] [numeric](19, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[DBID_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[JBPM4_PROPERTY]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[JBPM4_PROPERTY](
	[KEY_] [varchar](255) NOT NULL,
	[VERSION_] [numeric](10, 0) NOT NULL,
	[VALUE_] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[KEY_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[JBPM4_PARTICIPATION]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[JBPM4_PARTICIPATION](
	[DBID_] [numeric](19, 0) NOT NULL,
	[DBVERSION_] [numeric](10, 0) NOT NULL,
	[GROUPID_] [varchar](255) NULL,
	[USERID_] [varchar](255) NULL,
	[TYPE_] [varchar](255) NULL,
	[TASK_] [numeric](19, 0) NULL,
	[SWIMLANE_] [numeric](19, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[DBID_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[JBPM4_LOB]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
CREATE TABLE [dbo].[JBPM4_LOB](
	[DBID_] [numeric](19, 0) NOT NULL,
	[DBVERSION_] [numeric](10, 0) NOT NULL,
	[BLOB_VALUE_] [image] NULL,
	[DEPLOYMENT_] [numeric](19, 0) NULL,
	[NAME_] [text] NULL,
PRIMARY KEY CLUSTERED 
(
	[DBID_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];
/****** Object:  Table [dbo].[JBPM4_JOB]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[JBPM4_JOB](
	[DBID_] [numeric](19, 0) NOT NULL,
	[CLASS_] [varchar](255) NOT NULL,
	[DBVERSION_] [numeric](10, 0) NOT NULL,
	[DUEDATE_] [datetime] NULL,
	[STATE_] [varchar](255) NULL,
	[ISEXCLUSIVE_] [numeric](1, 0) NULL,
	[LOCKOWNER_] [varchar](255) NULL,
	[LOCKEXPTIME_] [datetime] NULL,
	[EXCEPTION_] [text] NULL,
	[RETRIES_] [numeric](10, 0) NULL,
	[PROCESSINSTANCE_] [numeric](19, 0) NULL,
	[EXECUTION_] [numeric](19, 0) NULL,
	[CFG_] [numeric](19, 0) NULL,
	[SIGNAL_] [varchar](255) NULL,
	[EVENT_] [varchar](255) NULL,
	[REPEAT_] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[DBID_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[JBPM4_ID_USER]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[JBPM4_ID_USER](
	[DBID_] [numeric](19, 0) NOT NULL,
	[DBVERSION_] [numeric](10, 0) NOT NULL,
	[ID_] [varchar](255) NULL,
	[PASSWORD_] [varchar](255) NULL,
	[GIVENNAME_] [varchar](255) NULL,
	[FAMILYNAME_] [varchar](255) NULL,
	[BUSINESSEMAIL_] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[DBID_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[JBPM4_ID_MEMBERSHIP]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[JBPM4_ID_MEMBERSHIP](
	[DBID_] [numeric](19, 0) NOT NULL,
	[DBVERSION_] [numeric](10, 0) NOT NULL,
	[USER_] [numeric](19, 0) NULL,
	[GROUP_] [numeric](19, 0) NULL,
	[NAME_] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[DBID_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[JBPM4_ID_GROUP]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[JBPM4_ID_GROUP](
	[DBID_] [numeric](19, 0) NOT NULL,
	[DBVERSION_] [numeric](10, 0) NOT NULL,
	[ID_] [varchar](255) NULL,
	[NAME_] [varchar](255) NULL,
	[TYPE_] [varchar](255) NULL,
	[PARENT_] [numeric](19, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[DBID_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[JBPM4_HIST_VAR]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[JBPM4_HIST_VAR](
	[DBID_] [numeric](19, 0) NOT NULL,
	[DBVERSION_] [numeric](10, 0) NOT NULL,
	[PROCINSTID_] [varchar](255) NULL,
	[EXECUTIONID_] [varchar](255) NULL,
	[VARNAME_] [varchar](255) NULL,
	[VALUE_] [varchar](255) NULL,
	[HPROCI_] [numeric](19, 0) NULL,
	[HTASK_] [numeric](19, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[DBID_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[JBPM4_HIST_TASK]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[JBPM4_HIST_TASK](
	[DBID_] [numeric](19, 0) NOT NULL,
	[DBVERSION_] [numeric](10, 0) NOT NULL,
	[EXECUTION_] [varchar](255) NULL,
	[OUTCOME_] [varchar](255) NULL,
	[ASSIGNEE_] [varchar](255) NULL,
	[PRIORITY_] [numeric](10, 0) NULL,
	[STATE_] [varchar](255) NULL,
	[CREATE_] [datetime] NULL,
	[END_] [datetime] NULL,
	[DURATION_] [numeric](19, 0) NULL,
	[NEXTIDX_] [numeric](10, 0) NULL,
	[SUPERTASK_] [numeric](19, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[DBID_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[JBPM4_HIST_PROCINST]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[JBPM4_HIST_PROCINST](
	[DBID_] [numeric](19, 0) NOT NULL,
	[DBVERSION_] [numeric](10, 0) NOT NULL,
	[ID_] [varchar](255) NULL,
	[PROCDEFID_] [varchar](255) NULL,
	[KEY_] [varchar](255) NULL,
	[START_] [datetime] NULL,
	[END_] [datetime] NULL,
	[DURATION_] [numeric](19, 0) NULL,
	[STATE_] [varchar](255) NULL,
	[ENDACTIVITY_] [varchar](255) NULL,
	[NEXTIDX_] [numeric](10, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[DBID_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[JBPM4_HIST_DETAIL]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[JBPM4_HIST_DETAIL](
	[DBID_] [numeric](19, 0) NOT NULL,
	[CLASS_] [varchar](255) NOT NULL,
	[DBVERSION_] [numeric](10, 0) NOT NULL,
	[USERID_] [varchar](255) NULL,
	[TIME_] [datetime] NULL,
	[HPROCI_] [numeric](19, 0) NULL,
	[HPROCIIDX_] [numeric](10, 0) NULL,
	[HACTI_] [numeric](19, 0) NULL,
	[HACTIIDX_] [numeric](10, 0) NULL,
	[HTASK_] [numeric](19, 0) NULL,
	[HTASKIDX_] [numeric](10, 0) NULL,
	[HVAR_] [numeric](19, 0) NULL,
	[HVARIDX_] [numeric](10, 0) NULL,
	[MESSAGE_] [varchar](255) NULL,
	[OLD_STR_] [varchar](255) NULL,
	[NEW_STR_] [varchar](255) NULL,
	[OLD_INT_] [numeric](10, 0) NULL,
	[NEW_INT_] [numeric](10, 0) NULL,
	[OLD_TIME_] [datetime] NULL,
	[NEW_TIME_] [datetime] NULL,
	[PARENT_] [numeric](19, 0) NULL,
	[PARENT_IDX_] [numeric](10, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[DBID_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[JBPM4_HIST_ACTINST]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[JBPM4_HIST_ACTINST](
	[DBID_] [numeric](19, 0) NOT NULL,
	[CLASS_] [varchar](255) NOT NULL,
	[DBVERSION_] [numeric](10, 0) NOT NULL,
	[HPROCI_] [numeric](19, 0) NULL,
	[TYPE_] [varchar](255) NULL,
	[EXECUTION_] [varchar](255) NULL,
	[ACTIVITY_NAME_] [varchar](255) NULL,
	[START_] [datetime] NULL,
	[END_] [datetime] NULL,
	[DURATION_] [numeric](19, 0) NULL,
	[TRANSITION_] [varchar](255) NULL,
	[NEXTIDX_] [numeric](10, 0) NULL,
	[HTASK_] [numeric](19, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[DBID_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[JBPM4_EXECUTION]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[JBPM4_EXECUTION](
	[DBID_] [numeric](19, 0) NOT NULL,
	[CLASS_] [varchar](255) NOT NULL,
	[DBVERSION_] [numeric](10, 0) NOT NULL,
	[ACTIVITYNAME_] [varchar](255) NULL,
	[PROCDEFID_] [varchar](255) NULL,
	[HASVARS_] [numeric](1, 0) NULL,
	[NAME_] [varchar](255) NULL,
	[KEY_] [varchar](255) NULL,
	[ID_] [varchar](255) NULL,
	[STATE_] [varchar](255) NULL,
	[SUSPHISTSTATE_] [varchar](255) NULL,
	[PRIORITY_] [numeric](10, 0) NULL,
	[HISACTINST_] [numeric](19, 0) NULL,
	[PARENT_] [numeric](19, 0) NULL,
	[INSTANCE_] [numeric](19, 0) NULL,
	[SUPEREXEC_] [numeric](19, 0) NULL,
	[SUBPROCINST_] [numeric](19, 0) NULL,
	[PARENT_IDX_] [numeric](10, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[DBID_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[ID_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[JBPM4_DEPLOYPROP]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[JBPM4_DEPLOYPROP](
	[DBID_] [numeric](19, 0) NOT NULL,
	[DEPLOYMENT_] [numeric](19, 0) NULL,
	[OBJNAME_] [varchar](255) NULL,
	[KEY_] [varchar](255) NULL,
	[STRINGVAL_] [varchar](255) NULL,
	[LONGVAL_] [numeric](19, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[DBID_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[JBPM4_DEPLOYMENT]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[JBPM4_DEPLOYMENT](
	[DBID_] [numeric](19, 0) NOT NULL,
	[NAME_] [varchar](255) NULL,
	[TIMESTAMP_] [numeric](19, 0) NULL,
	[STATE_] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[DBID_] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[CMS_CATEGORY]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[CMS_CATEGORY](
	[sid] [varchar](50) NULL,
	[category_title] [varchar](100) NOT NULL,
	[category_status] [varchar](10) NULL,
	[category_site] [varchar](50) NULL,
	[category_order] [int] NULL,
	[creator] [varchar](50) NULL,
	[creator_dept] [varchar](50) NULL,
	[create_time] [datetime] NULL
) ON [PRIMARY];
SET ANSI_PADDING OFF;
/****** Object:  Table [dbo].[CMS_ARTICLE]    Script Date: 07/14/2012 13:58:42 ******/
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
CREATE TABLE [dbo].[CMS_ARTICLE](
	[sid] [varchar](100) NULL,
	[article_title] [varchar](max) NULL,
	[article_content] [text] NULL,
	[create_date] [datetime] NULL,
	[modify_date] [datetime] NULL,
	[creator_name] [varchar](200) NULL,
	[article_keywords] [varchar](200) NULL,
	[article_resource] [varchar](200) NULL,
	[article_summary] [varchar](500) NULL,
	[creator_id] [varchar](100) NULL,
	[article_category] [varchar](100) NULL,
	[status] [varchar](100) NULL,
	[article_order] [int] NULL,
	[clicktime] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
SET ANSI_PADDING OFF
ALTER TABLE [dbo].[CMS_ARTICLE] ADD [article_att] [varchar](50) NULL;
SET ANSI_PADDING OFF;
/****** Object:  Default [DF__SYS_FILES__isper__1EA48E88]    Script Date: 07/14/2012 13:58:42 ******/
ALTER TABLE [dbo].[SYS_FILES] ADD  DEFAULT ((1)) FOR [ispermanent];
